/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "message.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(event, event, AUTO)


PB_BIND(command, command, AUTO)


PB_BIND(car_sensor, car_sensor, AUTO)


PB_BIND(stint_data, stint_data, AUTO)


PB_BIND(lap, lap, AUTO)


PB_BIND(lap_data, lap_data, AUTO)


PB_BIND(mcu_data, mcu_data, 2)






#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

